### PR TITLE
Add CI support for GHC 9.2

### PR DESCRIPTION
**Pull request by fendor**

### CODE REVIEW

**Comment by fendor** [comment]
I did not consider windows issues.

**Comment by jneira** [comment]
so we need a newer unix-compat for windows?

**Comment by fendor** [comment]
Yeah, I think there is a PR for it: https://github.com/jacobstanley/unix-compat/pull/47

**Comment by jneira** [comment]
so time to create a cabal-ghc902.project.local with the appropiate source-repo-package and allow-newer's?

**Comment by fendor** [comment]
We could if we are impatient.

**Comment by fendor** [comment]
For now superseded by #324

**Pull request closed without merging**
