### PR TITLE
Refactor parsing of hie.yaml files

### PR DESCRIPTION
**Pull request by ThomasCrevoisier**
Takes care of #315 

This introduces a `Hie.Bios.Config.YAML` module which defines datatypes a bit closer to the YAML structure.
It allows writing simpler FromJSON instances (without using CPP !) and should be equivalent to the types existing in the `Hie.Bios.Config` module.

### CODE REVIEW

**Comment by fendor** [comment]
Hi! Looking good!

Since CI has a failure, can you add the failing hie.yaml to the parser-tests? If I read this correctly, should be this one: https://github.com/haskell/hie-bios/blob/master/tests/projects/failing-cabal/hie.yaml

**Comment by ThomasCrevoisier** [comment]
@fendor all should be good now !

**Review by fendor — CHANGES_REQUESTED** [review]

**Comment by fendor** [comment]
Unfortunately, the generic variant suffers currently from the issue of ignoring unknown keys. Example:
```yaml
cradle:
  cabal:
    comp:
    - "exe:hie-bios"
```

is an invalid `hie.yaml`. 

and currently hie-bios reports:
```
hie-bios: AesonException "Error in $.cradle: Not a valid Cabal configuration, following keys are allowed: component"
```
but with this patch, this becomes:
``` 
Config {cradle = CradleConfig {cradleDependencies = [], cradleType = Cabal {component = Nothing}}}
``` 

It successfully parses, and ignores that you mistyped or misnamed the argument.

Can we do better than that?

**Comment by ThomasCrevoisier** [comment]
Oh I see. I've got few questions on this point.

As I've seen in the test suite, empty objects are allowed right ?

Regarding unknown keys, what should be the behavior when the object we provide contains a valid config but with extra keys that we will ignore ?

Failing on missing keys is pretty straightforward, but failing on extra unwanted keys might be a bit trickier to do.

**Comment by fendor** [comment]
> Regarding unknown keys, what should be the behavior when the object we provide contains a valid config but with extra keys that we will ignore ?

Until now, we threw an error message. The point being that you notice you didn't write the correct configuration and something is not right.
The idea being that subtle typos are discovered ASAP, and not just ignored.

At the moment, I think it is better if we throw an error if there are extra keys we don't know.

It is indeed trickier :/

**Comment by ThomasCrevoisier** [comment]
f2f16ecf9d80d2d56b29f821216b7c607c3ecb10 is a proposal for fixing this particular point.

The downside is that we have to duplicate a bit the keys between parsing and checking but the implementation is relatively simple.

Let me know what you think !

**Comment by fendor** [comment]
BTW, I did not forget, just didn't have time for an in-depth review (since this is important to get right). So far it looks good, and I am going to review in depth until the end of the weekend.

**Comment by ThomasCrevoisier** [comment]
Sure, absolutely no worries ! I won't be responsive this week-end, but I'll remain available to work on it next week :)

**Comment by fendor** [comment]
I see your point and did not consider this angle before. @ThomasCrevoisier Would it be hard to turn these errors into warnings?

**Review by fendor — APPROVED** [review]
As I don't want to keep you waiting, we are going to merge this as it is an improvement of the status-quo. We will create an issue for the remaining issue

**Comment by ThomasCrevoisier** [comment]
👋 Truely sorry @fendor, those past months have been quite busy and I forgot to come back to this PR 😞 

Feel free to move forward with it (I don't have any simple solution in mind regarding extra keys handling unfortunately), and again, sorry for the lack of reactivity.

**Comment by fendor** [comment]
No need to apologise, life can be stressful (speaking from experience), and we all deeply appreciate the time you have spent on this!

**Pull request merged**
