### PR TITLE
Issue/pr: attempt to ignore Setup.hs file with none cradle

### PR DESCRIPTION
**Pull request by codygman**
There was discussion about perhaps ignoring Setup.hs with `cradle: {none:}` in the #ide discord channel for Zurihac. This was an attempt at that, it results in:

```sh
[nix-shell:~/hie-bios/tests/projects/multi-cabal]$ cat hie.yaml 
cradle:
  multi:
    - path: "./Setup.hs"
      config: { cradle: { none:  } }
    - path: "./"
      config: { cradle: { cabal:
                            [ { path: "./src", component: "lib:multi-cabal" }
                            , { path: "./app", component: "exe:multi-cabal" } ] } }
[nix-shell:~/hie-bios/tests/projects/multi-cabal]$ hie-bios check Setup.hs
No cradle
```

If it's relevant, this is the ghcide output I get:

```sh
[nix-shell:~/hie-bios/tests/projects/multi-cabal]$ ghcide
ghcide version: 0.2.0 (GHC: 8.8.3) (PATH: /nix/store/y6jhrmc3fw926kmxvxsp9k5w3pfci2dz-ghcide-0.2.0/bin/ghcide)
Ghcide setup tester in /home/demo/hie-bios/tests/projects/multi-cabal.
Report bugs at https://github.com/digital-asset/ghcide/issues

Step 1/4: Finding files to test in /home/demo/hie-bios/tests/projects/multi-cabal
Found 3 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "/home/demo/hie-bios/tests/projects/multi-cabal/Setup.hs"
[INFO] Consulting the cradle for "/home/demo/hie-bios/tests/projects/multi-cabal/src/Lib.hs"
> Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
> update' to download it.RemoteRepo {remoteRepoName = "hackage.haskell.org",
> remoteRepoURI = http://hackage.haskell.org/, remoteRepoSecure = Just True,
> remoteRepoRootKeys =
> ["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
> remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
> Resolving dependencies...
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - multi-cabal-0.1.0.0 (lib) (configuration changed)
> Configuring library for multi-cabal-0.1.0.0..
> Preprocessing library for multi-cabal-0.1.0.0..
[INFO] Using interface files cache dir: /home/demo/.cache/ghcide/multi-cabal-0.1.0.0-inplace-cdfa6dcb1516eff92b399bd20ac4b64a15e9e1ac
[INFO] Making new HscEnv[multi-cabal-0.1.0.0-inplace]
[INFO] Consulting the cradle for "/home/demo/hie-bios/tests/projects/multi-cabal/app/Main.hs"
> Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
> update' to download it.RemoteRepo {remoteRepoName = "hackage.haskell.org",
> remoteRepoURI = http://hackage.haskell.org/, remoteRepoSecure = Just True,
> remoteRepoRootKeys =
> ["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
> remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}
> Resolving dependencies...
> Build profile: -w ghc-8.8.3 -O1
> In order, the following will be built (use -v for more details):
>  - multi-cabal-0.1.0.0 (lib) (configuration changed)
>  - multi-cabal-0.1.0.0 (exe:multi-cabal) (configuration changed)
> Configuring library for multi-cabal-0.1.0.0..
> Preprocessing library for multi-cabal-0.1.0.0..
> Building library for multi-cabal-0.1.0.0..
> Configuring executable 'multi-cabal' for multi-cabal-0.1.0.0..
> Warning: The package has an extraneous version range for a dependency on an
> internal library: multi-cabal -any && ==0.1.0.0. This version range includes
> the current package but isn't needed as the current package's library will
> always be used.
> Preprocessing executable 'multi-cabal' for multi-cabal-0.1.0.0..
[INFO] Using interface files cache dir: /home/demo/.cache/ghcide/main-aca466b03fb8f6133c402efa240ff6b578b334c1
[INFO] Using interface files cache dir: /home/demo/.cache/ghcide/multi-cabal-0.1.0.0-inplace-5fdf08788779441486913c11ae82348a401b2c37
[INFO] Making new HscEnv[main,multi-cabal-0.1.0.0-inplace]
Files that failed:
 * /home/demo/hie-bios/tests/projects/multi-cabal/Setup.hs

Completed (2 files worked, 1 file failed)
```

I'm using nix obviously, but it's not necessary for others, just an option if we need things to be reproducible. But wanted to ensure things were reproducible. Here are the versions I'm working with if you don't have or don't want `nix-shell` already:

```sh

hie-bios version 0.5.0 compiled by GHC 8.8.3

The Glorious Glasgow Haskell Compilation System, version 8.8.3

cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 

ghcide version: 0.2.0 (GHC: 8.8.3)
```

### CODE REVIEW

**Comment by fendor** [comment]
I am not quite sure what the purpose of this PR. Adding an example of what the hie.yaml file might look like? Then it should rather be added to the README as its discoverability and purpose is non obvious in a test.

Also, I think it would be better do have a dedicated none-cradle test.

**Comment by codygman** [comment]
> I am not quite sure what the purpose of this PR. Adding an example of what the hie.yaml file might look like? Then it should rather be added to the README as its discoverability and purpose is non obvious in a test.
> 
> Also, I think it would be better do have a dedicated none-cradle test.

You're right, I just wanted to make sure I was doing things correctly and possibly provide an example. It was really late and I wanted some sort of placeholder at the least for this issue.

**Comment by fendor** [comment]
> You're right, I just wanted to make sure I was doing things correctly

This is correct, I've used it before myself :)

**Comment by jneira** [comment]
Well maybe a thing we could change (in ghcide/hls) is the message
```
Files that failed:
 * /home/demo/hie-bios/tests/projects/multi-cabal/Setup.hs
```
Itis a bit misleading cause if you set a none cradle on purpose, not loading the file is succesful.

**Comment by fendor** [comment]
@jneira I am pretty sure that is a ghcide/hls issue

**Pull request closed without merging**
