### PR TITLE
WIP for cabal show-build-info

### PR DESCRIPTION
**Pull request by fendor**
Use features from https://github.com/haskell/cabal/pull/7478

Starts work on #269

### CODE REVIEW

**Comment by georgefst** [comment]
I'm curious, with upstream support in Cabal seemingly now implemented, is there anything blocking this? There are a lot of issues in HLS which mention this as the solution.

**Comment by fendor** [comment]
Yeah, there are unfortunately a couple of open issues :sweat_smile: Also, #255 essentially implements proper multi-home unit support without `show-build-info`.

**Comment by georgefst** [comment]
But #409 doesn't solve the issue of the user having to manually load all the right components to prevent errors like https://github.com/haskell/haskell-language-server/issues/1370. I thought the point of `show-build-info` was that it finally gives us the information we need in order to know which components to load.

**Comment by georgefst** [comment]
> But #409 doesn't solve the issue of the user having to manually load all the right components to prevent errors like [haskell/haskell-language-server#1370](https://github.com/haskell/haskell-language-server/issues/1370).

Or maybe it does? I just noticed from https://github.com/haskell/haskell-language-server/issues/3738 that the latest HLS release doesn't incorporate those commits yet.

**Comment by fendor** [comment]
> But https://github.com/haskell/hie-bios/pull/409 doesn't solve the issue of the user having to manually load all the right components to prevent errors like https://github.com/haskell/haskell-language-server/issues/1370. I thought the point of show-build-info was that it finally gives us the information we need in order to know which components to load.

It does! Conceptually, `cabal repl --enable-multi-repl` computes all the components you need to load into ghci, invokes ghci via `ghci @args.unitA.txt @args.unitB.txt` and HLS simply looks at these args and sets up the session appropriately.
Currently, the only advantage seems to be that `show-build-info` uses a well-defined interface instead of the hacky `cabal repl -w hie-bios-ghc` solution.

**Comment by georgefst** [comment]
Aha, awesome! Well then, I very much look forward to HLS being released with the new hie-bios.

**Pull request closed without merging**
